// Type defnitions for items used for Preferences and other data structures
pub mod material {
    use crate::types::flagarray::FlagArray;

    pub enum MaterialState {
        Any = -1,
        Solid,
        Liquid,
        Gas,
        Powder,
        Paste,
        Pressed
    }
    pub enum MaterialFlag {
        None = -1,
        Bone = 0,
        Meat = 1,
        EdibleVermin = 2,
        EdibleRaw = 3,
        EdibleCooked = 4,
        Alcohol = 5,
        ItemsMetal = 6,
        ItemsBarred = 7,
        ItemsScaled = 8,
        ItemsLeather = 9,
        itemsSoft = 10,
        ItemsHard = 11,
        IMPLIES_ANIMAL_KILL = 12,
        ALCOHOL_PLANT = 13,
        ALCOHOL_CREATURE = 14,
        CHEESE_PLANT = 15,
        CHEESE_CREATURE = 16,
        POWDER_MISC_PLANT = 17,
        POWDER_MISC_CREATURE = 18,
        STOCKPILE_GLOB = 19,
        LIQUID_MISC_PLANT = 20,
        LIQUID_MISC_CREATURE = 21,
        LIQUID_MISC_OTHER = 22,
        IS_WOOD = 23,
        THREAD_PLANT = 24,
        TOOTH = 25,
        HORN = 26,
        PEARL = 27,
        SHELL = 28,
        LEATHER = 29,
        SILK = 30,
        SOAP = 31,
        ROTS = 32,
        IS_DYE = 33,
        IS_POWDER_MISC = 34,
        IS_LIQUID_MISC = 35,
        STRUCTURAL_PLANT_MAT = 36,
        SEED_MAT = 37,
        LEAF_MAT = 38,
        IS_CHEESE = 39,
        ENTERS_BLOOD = 40,
        BLOOD_MAP_DESCRIPTOR = 41,
        ICHOR_MAP_DESCRIPTOR = 42,
        GOO_MAP_DESCRIPTOR = 43,
        SLIME_MAP_DESCRIPTOR = 44,
        PUS_MAP_DESCRIPTOR = 45,
        GENERATES_MIASMA = 46,
        IS_METAL = 47,
        IS_GEM = 48,
        IS_GLASS = 49,
        CRYSTAL_GLASSABLE = 50,
        ITEMS_WEAPON = 51,
        ITEMS_WEAPON_RANGED = 52,
        ITEMS_ANVIL = 53,
        ITEMS_AMMO = 54,
        ITEMS_DIGGER = 55,
        ITEMS_ARMOR = 56,
        ITEMS_DELICATE = 57,
        ITEMS_SIEGE_ENGINE = 58,
        ITEMS_QUERN = 59,
        IS_STONE = 60,
        UNDIGGABLE = 61,
        YARN = 62,
        STOCKPILE_GLOB_PASTE = 63,
        STOCKPILE_GLOB_PRESSED = 64,
        DISPLAY_UNGLAZED = 65,
        DO_NOT_CLEAN_GLOB = 66,
        NO_STONE_STOCKPILE = 67,
        STOCKPILE_THREAD_METAL = 68,
        NUM_OF_MATERIAL_FLAGS = 69
    }

    #[derive(Default, Debug)]
    pub struct Material {
        pub id: i32,
        pub addr: usize,
        pub flags: FlagArray,
        pub inorganic: bool,
    }
}
use std::hash::Hash;

#[derive(Default, Debug, Eq, PartialEq, Hash)]
pub enum ItemType {
    #[default]
    None = -1,
    Bar,
    SmallGem,
    Blocks,
    Rough,
    Boulder,
    Wood,
    Door,
    FloodGate,
    Bed,
    Chair,
    Chain,
    Flask,
    Goblet,
    Instrument,
    Toy,
    Window,
    Cage,
    Barrel,
    Bucket,
    AnimalTrap,
    Table,
    Coffin,
    Statue,
    Corpse,
    Weapon,
    Armor,
    Shoes,
    Shield,
    Helm,
    Gloves,
    Box,
    Bag,
    Bin,
    ArmorStand,
    WeaponRack,
    Cabinet,
    Figurine,
    Amulet,
    Scepter,
    Ammo,
    Crown,
    Ring,
    Earring,
    Bracelet,
    Gem,
    Anvil,
    CorpsePiece,
    Remains,
    Meat,
    Fish,
    FishRaw,
    Vermin,
    IsPet,
    Seeds,
    Plant,
    SkinTanned,
    LeavesFruit,
    Thread,
    Cloth,
    Totem,
    Pants,
    Backpack,
    Quiver,
    CatapultParts,
    BallistaParts,
    SiegeAmmo,
    BallistaArrowhead,
    TrapParts,
    TrapComp,
    Drink,
    PowderMisc,
    Cheese,
    Food,
    LiquidMisc,
    Coin,
    Glob,
    Rock,
    PipeSection,
    HatchCover,
    Grate,
    Quern,
    Millstone,
    Splint,
    Crutch,
    TractionBench,
    OrthopedicCast,
    Tool,
    Slab,
    Egg,
    Book,
    Sheet,
    NumOfItemTypes,
    Supplies = 999,
    Artifacts = 1000,
    MeleeEquipment = 1001,
    RangedEquipment = 1002,
    Vial = 1006,
    Waterskin = 1007
}